import type { Article } from '../types'

export const ARTICLES: Article[] = [
  {
    id: 'porter-what-is-strategy-1',
    title: 'Что такое стратегия? Часть I',
    authors: 'Майкл Портер',
    source: 'Harvard Business Review',
    year: '1996',
    lectureIds: [1, 7],
    thesis: 'Операционная эффективность необходима, но недостаточна — только уникальная стратегическая позиция с trade-offs создаёт устойчивое конкурентное преимущество.',
    keyPoints: [
      'ОЭ ≠ стратегия: когда все копируют лучшие практики, отрасль сходится к одной «границе производительности»',
      'Конкурентная конвергенция → взаимоистощающая конкуренция без победителей',
      'Стратегическая позиция = уникальный набор активностей, отличный от конкурентов',
      'Trade-offs защищают позицию: осознанные отказы делают копирование невозможным',
      'Fit (согласованность) между активностями усиливает позицию и снижает риск имитации',
      'Рост — угроза стратегии: давление «делать больше» разрушает фокус',
    ],
    quote: 'Operational effectiveness means performing similar activities better than rivals perform them. Strategic positioning means performing different activities from rivals, or performing similar activities in different ways.',
    examRelevance: 'Ч.1: Q1 демо — конкурентная конвергенция. Ч.3: «операционная эффективность» vs «стратегическое позиционирование». Ч.2: what protects a position — trade-offs.',
  },
  {
    id: 'porter-what-is-strategy-2',
    title: 'Что такое стратегия? Часть II',
    authors: 'Майкл Портер',
    source: 'Harvard Business Review',
    year: '1996',
    lectureIds: [1, 7],
    thesis: 'Три источника стратегической позиции: потребностное, доступное и разновидностное позиционирование — каждый требует согласованной системы активностей.',
    keyPoints: [
      'Потребностное позиционирование: обслуживать особые потребности особого сегмента (IKEA — молодые покупатели)',
      'Доступное позиционирование: обслуживать клиентов с иным доступом (сельские vs городские)',
      'Разновидностное позиционирование: производить особый набор продуктов/услуг',
      'Activity system map: взаимосвязанные активности как карта стратегии',
      'Стратегические позиции требуют выбора — иначе не позиции',
      'Лидерство — главная угроза стратегии: CEO должен уметь говорить «нет»',
    ],
    quote: 'The essence of strategy is choosing what not to do. Without trade-offs, there would be no need for choice and thus no need for strategy.',
    examRelevance: 'Ч.2: согласованность (fit) активностей. Ч.1: типы стратегического позиционирования.',
  },
  {
    id: 'collins-porras-vision',
    title: 'Building Your Company\'s Vision',
    authors: 'Джим Коллинз & Джерри Поррас',
    source: 'Harvard Business Review',
    year: '1996',
    lectureIds: [2],
    thesis: 'Компании-лидеры разделяют ключевую идеологию (неизменную) и энвизионируемое будущее (изменяемое), якорем которого является BHAG.',
    keyPoints: [
      'Ключевая идеология = миссия (почему существуем) + ценности (как действуем) — не меняется 50+ лет',
      'Энвизионируемое будущее = BHAG + яркое описание',
      'BHAG: Big Hairy Audacious Goal — дерзкая, конкретная цель на 10–30 лет',
      'Компании-пионеры vs последователи: разница в ясности идеологии, а не в гениальности основателей',
      'Ошибка: менять миссию ради текущих рыночных трендов',
      'Прибыль — не цель, а результат: идеологические компании прибыльнее',
    ],
    quote: 'A BHAG engages people — it reaches out and grabs them in the gut. It is tangible, energizing, highly focused. People "get it" right away; it takes little or no explanation.',
    examRelevance: 'Ч.3: Q20 демо — BHAG, авторы Коллинз & Поррас. Ч.1: иерархия целей, отличие BHAG от видения.',
  },
  {
    id: 'kim-mauborgne-blue-ocean',
    title: 'Стратегия голубого океана',
    authors: 'В. Чан Ким & Рене Моборн',
    source: 'Harvard Business Review',
    year: '2004 / книга 2005',
    lectureIds: [7],
    thesis: 'Ценностная инновация — одновременный рост ценности для покупателей и снижение издержек через реконструкцию отраслевых границ с помощью ERRC.',
    keyPoints: [
      'Красный океан: конкуренция за существующий спрос — нулевая сумма',
      'Голубой океан: новое бесконкурентное пространство — ненулевая сумма',
      'Ценностная инновация ≠ дифференциация: нет ценового компромисса (снижаем издержки И растим ценность)',
      'ERRC-сетка: Eliminate / Reduce / Raise / Create',
      'Стратегическая канва: визуализация текущего vs нового профиля ценности',
      'Реконструкционистский взгляд: рыночные границы НЕ фиксированы',
      'Cirque du Soleil — эталонный пример: устранили животных/звёзды, создали художественную атмосферу',
    ],
    quote: 'Value innovation is the cornerstone of blue ocean strategy. It is called value innovation because instead of focusing on beating the competition, you focus on making the competition irrelevant by creating a leap in value for buyers and your company.',
    examRelevance: 'Ч.3: Q23 — ценностная инновация, авторы Ким & Моборн. Ч.1: ERRC по описанию; отличить от дифференциации.',
  },
  {
    id: 'prahalad-hamel-core-competence',
    title: 'Ключевая компетенция корпорации',
    authors: 'К.К. Прахалад & Гэри Хамел',
    source: 'Harvard Business Review',
    year: '1990',
    lectureIds: [5, 9],
    thesis: 'Корпорация — не портфель бизнесов, а портфель компетенций; ключевые компетенции обеспечивают доступ к широкому кругу рынков.',
    keyPoints: [
      '3 теста ключевой компетенции: доступ к рынкам, вклад в ценность для клиента, сложность имитации',
      'Дерево компетенций: корни → ствол → ветви → листья (продукты)',
      'Honda: компетенция в двигателях → мотоциклы, авто, газонокосилки, генераторы',
      'Угроза «аутсорсинга компетенций»: конкуренты поглощают ваши ключевые знания',
      'Корпоративный менеджмент должен беречь компетенции, а не просто управлять портфелем',
    ],
    quote: 'Core competences are the collective learning in the organization, especially how to coordinate diverse production skills and integrate multiple streams of technologies.',
    examRelevance: 'Ч.3: ключевая компетенция + авторы Прахалад & Хамел. Ч.2: связь с VRIO и родительским преимуществом.',
  },
  {
    id: 'brandenburger-strengths-weaknesses',
    title: 'Are Your Strengths Really Weaknesses?',
    authors: 'Адам Бранденбургер',
    source: 'Harvard Business Review',
    year: '2024',
    lectureIds: [5],
    thesis: 'Сильные стороны компании могут оказаться слабостями, если конкуренты умело их эксплуатируют или если среда изменилась.',
    keyPoints: [
      'Сила → слабость при изменении среды (ключевые ригидности, Леонард-Бартон)',
      'Конкурент может «зеркалить» вашу силу: копировать форму без содержания',
      'Парадокс Икара (Миллер): успех порождает зависимость, зависимость порождает провал',
      'Необходима постоянная переоценка: остаётся ли ресурс ценным (V в VRIO)?',
    ],
    quote: 'The very things that make companies strong today can be the source of their greatest vulnerabilities tomorrow.',
    examRelevance: 'Ч.1/5: парадокс Икара. Ч.2: когда VRIO-ресурс перестаёт быть ценным.',
  },
  {
    id: 'johnson-christensen-kagermann',
    title: 'Обновление бизнес-модели',
    authors: 'Марк Джонсон, Клейтон Кристенсен & Хеннинг Кагерманн',
    source: 'Harvard Business Review',
    year: '2008',
    lectureIds: [8],
    thesis: 'Компании упускают возможности роста, потому что не понимают, когда нужно менять бизнес-модель, а не улучшать продукт.',
    keyPoints: [
      '4 блока бизнес-модели: CVP (ценностное предложение), формула прибыли, ключевые ресурсы, ключевые процессы',
      '5 сигналов для смены модели: новый сегмент, новая технология, подрыв снизу, регуляторные изменения, необходимость нового CVP',
      'Новая модель требует новой организационной единицы — нельзя встроить в старую',
      'Apple iPod/iTunes: новая модель (не просто продукт), опирающаяся на лицензионные соглашения',
      'Ловушка: улучшать продукт вместо смены модели',
    ],
    quote: 'Companies that fail to recognize the need for new business models can lose out to competitors even when they are winning on product features and execution.',
    examRelevance: 'Ч.1/8: когда нужна смена модели vs улучшение продукта. Ч.3: 4 блока бизнес-модели.',
  },
]

export function getArticle(id: string): Article | undefined {
  return ARTICLES.find(a => a.id === id)
}

export function getArticlesByLecture(lectureId: number): Article[] {
  return ARTICLES.filter(a => a.lectureIds.includes(lectureId))
}
